services:
  - type: static
    name: my-vite-react-app
    env: static
    buildCommand: npm run build
    publish: dist
    redirects:
      - source: /*
        destination: /index.html
        status: 200
